### ISSUE TITLE
Usability improvements

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-zaster#14]
Hi, 

i think that in the area of usability there is place for some improvement. When supporting only a single bank it was ok to login to the account in when starting the app. However, with multi bank support it does not make sense in my opinion, to be forced to log in to the last active account. With multibank support i would expect the following behaviour:

* when starting the app you always get an account overview page where you see the list of all the accounts  you created. which more or less looks like the current settings account. There it should be possible to add a new account via a global pulley menu. The existing accounts should be removable via a pulley at the account. 
* selecting a bank account from this screen will take the user to the login page for the account (just like it is at the moment) - but without the "remove account" button and the option to go back to the account overview. Once you entered the pin you will get the bankaccounts of the defined account - from here on it is the same as before. you can enter the transactions, and can come back.
* the pulley with the settings can then be removed, because you more or less can always go back to the account overview.

This workflow does feel much more natural to me. The current version 0.2 is (at least for me) very cumbersome to use when you have multiple accounts - because switch accounts is cumbersome. 

At the moment you start the app and have to log in the the active account even though you do not want to have a look at the last active account, because you wan to check a different account. So you have to log in to be able switch to a different  the account - which does not make sense.

Just my two cents, but i think the proposed changes do acutally do make sense, do they?

Cheers,
Andreas

**Comment by Wunderfitz** [comment]
Yeah well, these changes make more or less sense. Most certainly, I would do it slightly differently, but in general you need the account selection on the PIN/password screen. Removing the settings options won't happen - just because future versions most certainly will also have other settings. 

The problem is that I'm quite busy the next days and weeks and these changes won't happen soon because of that. The current state of 0.2 was also related to that. I simply wanted to have account switching available before I have other priorities. Of course, I'm open to pull requests in case somebody needs it urgently.
